### ISSUE TITLE
TypeError with `to_whois_dict()`

### ISSUE THREAD

**Issue by ninoseki** [pogzyb/whodap#29]
Hello, thanks for creating this library. Let me report an issue with `to_whois_dict()` method.

```py
import whodap

response = whodap.lookup_domain(domain='namesilo', tld='com')
print(response.to_whois_dict())
```

This code always fails because of the following TypeError.

```
Traceback (most recent call last):
  File "/tmp/whodap/test.py", line 4, in <module>
    print(response.to_whois_dict())
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/whodap/whodap/response.py", line 190, in to_whois_dict
    flat.update(self._flat_entities(self.entities))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/whodap/whodap/response.py", line 236, in _flat_entities
    for vcard in entity.vcardArray[-1]:
                 ~~~~~~~~~~~~~~~~~^^^^
TypeError: 'DomainResponse' object is not subscriptable
```

Probably something wrong with `_flat_entities()` logic.

**Comment by pogzyb** [comment]
Hi - I'm glad that this library is able to help you! 

This is a tricky situation that the library doesn't handle well. The issue isn't with completely with the `to_whois_dict` method, but due to the fact that the response does not conform to the RDAP spec.

Here is a snippet from the output from [rdap-conformance-tool](https://github.com/icann/rdap-conformance-tool/tree/master) for this domain. Command: `java -jar rdapct-1.0.jar -c ./rdapct-config.json https://www.namesilo.com/rdap/domain/namesilo.com`:
```
"results": {
        "warning": [
            {
                "code": -12210,
                "notes": "Domain includes invalid Entities array; See errors for details.",
                "message": "The value for the JSON name value does not pass #/entities/2/vcardArray validation [stdRdapEntitiesValidation].",
                "value": "#/entities/2/vcardArray:{\"properties\":[{\"name\":\"FN\",\"value\":{\"stringValue\":\"Domain Administrator\",\"typeName\":\"text\"}},{\"name\":\"ADR\",\"value\":{\"components\":[{\"name\":\"pobox\",\"value\":{\"typeName\":\"text\"}},{\"name\":\"ext\",\"value\":{\"typeName\":\"text\"}},{\"name\":\"street\",\"value\":{\"values\":[{\"stringValue\":\"1300 E. Missouri Avenue\",\"typeName\":\"text\"},{\"stringValue\":\"Suite A-110\",\"typeName\":\"text\"}],\"typeName\":\"text\"}},{\"name\":\"locality\",\"value\":{\"values\":[{\"stringValue\":\"Phoenix\",\"typeName\":\"text\"}],\"typeName\":\"text\"}},{\"name\":\"region\",\"value\":{\"values\":[{\"stringValue\":\"AZ\",\"typeName\":\"text\"}],\"typeName\":\"text\"}},{\"name\":\"code\",\"value\":{\"values\":[{\"stringValue\":\"85014\",\"typeName\":\"text\"}],\"typeName\":\"text\"}},{\"name\":\"country\",\"value\":{\"values\":[{\"stringValue\":\"US\",\"typeName\":\"text\"}],\"typeName\":\"text\"}}],\"typeName\":\"text\"}},{\"name\":\"ORG\",\"value\":{\"components\":[{\"name\":\"name\",\"value\":{\"stringValue\":\"NameSilo, LLC\",\"typeName\":\"text\"}}],\"typeName\":\"text\"}},{\"name\":\"TEL\",\"parameters\":{},\"value\":{\"stringValue\":\"tel:+0.8884626950\",\"typeName\":\"uri\"}},{\"name\":\"EMAIL\",\"value\":{\"stringValue\":\"internal_domains@namesilo.com\",\"typeName\":\"text\"}}]}"
            },
...
```
Specifically, the `vcardArray` doesn't follow [RFC 9083](https://datatracker.ietf.org/doc/html/rfc9083#name-the-entity-object-class)
![Screenshot from 2023-09-29 11-03-38](https://github.com/pogzyb/whodap/assets/12061211/0c81aa15-775c-48e0-8dc6-f27c2d44d2d1)

The response for the example you shared:
![Screenshot from 2023-09-29 11-04-06](https://github.com/pogzyb/whodap/assets/12061211/7fd27dd3-594c-45d7-bc66-4883af8bbe02)

Anyway, this information probably isn't relevant to what you actually need from this library :)

@ninoseki as a user of this library, what would you prefer the expected behaviour to be in these scenarios? Do you think raising an exception like `RDAPConformanceException` would be a good approach here? This way your applications could react accordingly (defaulting to using WHOIS or stop execution entirely). Right now, I definitely think the `TypeError` is misleading and not handling the underlying issue.

**Comment by ninoseki** [comment]
As a user, yes I'd like to have `RDAPConformanceException` rather than `TypeError`.
Also I think it's better to have strict and non-strict mode.
- strict: raises `RDAPConformanceException` for invalid format
- no-strict: creates lossy whois dict

**Comment by pogzyb** [comment]
I added a first draft of `strict=True/False` to the `to_whois_dict` method. It's not perfect and I have plans for improvements, but those improvements will require more time and effort, so I thought this solution would work for now. 

Please open more issues if needed. Thanks for using the library!
